"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DATA_VALIDATION_OPTIONS = exports.HTTP_RESPONSE_CODES = exports.ApiResponseCodeType = void 0;
var ApiResponseCodeType;
(function (ApiResponseCodeType) {
    ApiResponseCodeType[ApiResponseCodeType["SUCCESS"] = 0] = "SUCCESS";
    ApiResponseCodeType[ApiResponseCodeType["FAILED"] = 1] = "FAILED";
    ApiResponseCodeType[ApiResponseCodeType["ERROR"] = 2] = "ERROR";
})(ApiResponseCodeType = exports.ApiResponseCodeType || (exports.ApiResponseCodeType = {}));
var HTTP_RESPONSE_CODES;
(function (HTTP_RESPONSE_CODES) {
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["OK"] = 200] = "OK";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["BAD_REQUEST"] = 400] = "BAD_REQUEST";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["FORBIDDEN"] = 403] = "FORBIDDEN";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["NOT_FOUND"] = 404] = "NOT_FOUND";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["METHOD_NOT_ALLOWED"] = 405] = "METHOD_NOT_ALLOWED";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["NOT_IMPLEMENTED"] = 501] = "NOT_IMPLEMENTED";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["BAD_GATEWAY"] = 502] = "BAD_GATEWAY";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["REQUEST_CONFLICT"] = 409] = "REQUEST_CONFLICT";
    HTTP_RESPONSE_CODES[HTTP_RESPONSE_CODES["UNPROCESSABLE_ENTITY"] = 422] = "UNPROCESSABLE_ENTITY";
})(HTTP_RESPONSE_CODES = exports.HTTP_RESPONSE_CODES || (exports.HTTP_RESPONSE_CODES = {}));
exports.DATA_VALIDATION_OPTIONS = {
    abortEarly: true,
    stripUnknown: true,
};
